In [1]:
import pandas as pd

general = pd.read_excel("../raw/general_amps.xlsx")
antimicrobial = pd.read_excel("../raw/Antimicrobial_amps.xlsx")

print("General:", general.shape)
print("Antimicrobial:", antimicrobial.shape)

print("\nGeneral Columns:")
print(general.columns.tolist())

print("\nAntimicrobial Columns:")
print(antimicrobial.columns.tolist())

General: (11612, 27)
Antimicrobial: (5626, 27)

General Columns:
['DRAMP_ID', 'Sequence', 'Sequence_Length', 'Name', 'Swiss_Prot_Entry', 'Family', 'Gene', 'Source', 'Activity', 'Protein_existence', 'Structure', 'Structure_Description', 'PDB_ID', 'Comments', 'Target_Organism', 'Hemolytic_activity', 'Linear/Cyclic/Branched', 'N-terminal_Modification', 'C-terminal_Modification', 'Other_Modifications', 'Stereochemistry', 'Cytotoxicity', 'Binding_Traget', 'Pubmed_ID', 'Reference', 'Author', 'Title']

Antimicrobial Columns:
['DRAMP_ID', 'Sequence', 'Sequence_Length', 'Name', 'Swiss_Prot_Entry', 'Family', 'Gene', 'Source', 'Activity', 'Protein_existence', 'Structure', 'Structure_Description', 'PDB_ID', 'Comments', 'Target_Organism', 'Hemolytic_activity', 'Linear/Cyclic/Branched', 'N-terminal_Modification', 'C-terminal_Modification', 'Other_Modifications', 'Stereochemistry', 'Cytotoxicity', 'Binding_Traget', 'Pubmed_ID', 'Reference', 'Author', 'Title']

In [2]:
import pandas as pd

general = pd.read_excel("../raw/general_amps.xlsx")

# Keep only needed columns
df = general[
    [
        "DRAMP_ID",
        "Sequence",
        "Sequence_Length",
        "Activity",
        "Hemolytic_activity",
        "Target_Organism"
    ]
].copy()

print(df.shape)

# Remove missing sequences
df = df.dropna(subset=["Sequence"])

# Remove duplicates
df = df.drop_duplicates(subset=["Sequence"])

print("After deduplication:", df.shape)

df.head()

(11612, 6)
After deduplication: (10723, 6)

,DRAMP_ID,Sequence,Sequence_Length,Activity,Hemolytic_activity,Target_Organism
0,DRAMP00005,SLGPAIKATRQVCPKATRFVTVSCKKSDCQ,30,"Antimicrobial, Antibacterial, Anti-Gram+",No hemolysis information or data found in the ...,Gram-positive bacteria: Staphylococcus simulan...
1,DRAMP00017,VTSWSLCTPGCTSPGGGSNCSFCC,24,"Antimicrobial, Antibacterial",No hemolysis information or data found in the ...,Human pathogens: L100 Staphylococcus aureus AT...
2,DRAMP00032,GNGVLKTISHECNMNTWQFLFTCC,24,"Antimicrobial, Antibacterial, Anti-Gram+",No hemolysis information or data found in the ...,Gram-positive bacteria: Bifidobacterium longum...
3,DRAMP00063,SSSGWLCTLTIECGTIICACR,21,"Antimicrobial, Antibacterial",No hemolysis information or data found in the ...,Clavibacter michiganensis subspecies sepedonic...
4,DRAMP00068,MSWLNFLKYIAKYGKKAVSAAWKYKGKVLEWLNVGPTLEWVWQKLK...,51,"Antimicrobial, Antibacterial, Anti-Gram+",[Ref.12054867] No hemolytic activity was detec...,Gram-positive bacteria: Listeria monocytogenes...

In [3]:
print(df["Sequence_Length"].describe())

count    10723.000000
mean        25.917374
std         17.755135
min          2.000000
25%         14.000000
50%         20.000000
75%         32.000000
max        105.000000
Name: Sequence_Length, dtype: float64

In [4]:
invalid = df[
    ~df["Sequence"].str.match(r"^[ACDEFGHIKLMNPQRSTVWY]+$", na=False)
]

print("Invalid sequences:", len(invalid))

invalid.head()

Invalid sequences: 1554

,DRAMP_ID,Sequence,Sequence_Length,Activity,Hemolytic_activity,Target_Organism
29,DRAMP00244,XTPATPFTPAITEITAAVIAX,21,"Antimicrobial, Antibacterial, Anti-Gram+",No hemolysis information or data found in the ...,Gram-positive bacteria: Staphylococcus aureus ...
656,DRAMP02393,GFFKKAWRKVKHAGRRVLDTAKGVGRHYVNNWLNRYRZ,38,"Antimicrobial, Antibacterial, Anti-Gram+, Anti...",No hemolysis information or data found in the ...,Gram-positive bacteria: Propionibacterium acne...
657,DRAMP02394,GWFKKAWRKVKNAGRRVLKGVGIHYGVGLIZ,31,"Antimicrobial, Antibacterial, Anti-Gram+, Anti...",No hemolysis information or data found in the ...,Gram-positive bacteria: Propionibacterium acne...
719,DRAMP02843,ILKKWPWWPWRRKX,14,"Antimicrobial, Antibacterial, Anti-Gram+, Anti...",No hemolysis information or data found in the ...,Gram-negative bacteria: Escherichia coli (MIC=...
721,DRAMP02845,ICLKKWPWWPWRRCKX,16,"Antimicrobial, Antibacterial, Anti-Gram+, Anti...",No hemolysis information or data found in the ...,Gram-negative bacteria: Escherichia coli (MIC=...

In [5]:
VALID_AA = set("ACDEFGHIKLMNPQRSTVWY")

clean_df = df[
    df["Sequence"].apply(
        lambda seq: isinstance(seq, str) and set(seq).issubset(VALID_AA)
    )
].copy()

print("After AA filtering:", clean_df.shape)

clean_df = clean_df[
    (clean_df["Sequence_Length"] >= 5)
    & (clean_df["Sequence_Length"] <= 60)
].copy()

print("After length filtering:", clean_df.shape)

clean_df.reset_index(drop=True, inplace=True)

clean_df.head()

After AA filtering: (9169, 6)
After length filtering: (8400, 6)

,DRAMP_ID,Sequence,Sequence_Length,Activity,Hemolytic_activity,Target_Organism
0,DRAMP00005,SLGPAIKATRQVCPKATRFVTVSCKKSDCQ,30,"Antimicrobial, Antibacterial, Anti-Gram+",No hemolysis information or data found in the ...,Gram-positive bacteria: Staphylococcus simulan...
1,DRAMP00017,VTSWSLCTPGCTSPGGGSNCSFCC,24,"Antimicrobial, Antibacterial",No hemolysis information or data found in the ...,Human pathogens: L100 Staphylococcus aureus AT...
2,DRAMP00032,GNGVLKTISHECNMNTWQFLFTCC,24,"Antimicrobial, Antibacterial, Anti-Gram+",No hemolysis information or data found in the ...,Gram-positive bacteria: Bifidobacterium longum...
3,DRAMP00063,SSSGWLCTLTIECGTIICACR,21,"Antimicrobial, Antibacterial",No hemolysis information or data found in the ...,Clavibacter michiganensis subspecies sepedonic...
4,DRAMP00068,MSWLNFLKYIAKYGKKAVSAAWKYKGKVLEWLNVGPTLEWVWQKLK...,51,"Antimicrobial, Antibacterial, Anti-Gram+",[Ref.12054867] No hemolytic activity was detec...,Gram-positive bacteria: Listeria monocytogenes...

In [6]:
hemo = clean_df["Hemolytic_activity"].fillna("")

print("Total samples:", len(hemo))

print(
    hemo.str.contains(
        "hemolytic|hemolysis",
        case=False,
        na=False
    ).sum()
)

Total samples: 8400
6153

In [7]:
clean_df["Hemolytic_activity"].sample(
    20,
    random_state=42
).tolist()

['No hemolysis information or data found in the reference(s) presented in this entry',
 'No hemolysis information or data found in the reference(s) presented in this entry',
 '[Ref.33285267]2% hemolysis against mouse erythrocytes at 256 µM.',
 'No hemolysis information or data found in the reference(s) presented in this entry',
 '[Ref.31163671] 10% hemolysis at >100  μg/mL against human blood cells.',
 'No hemolysis information or data found in the reference(s) presented in this entry',
 'No hemolysis information or data found in the reference(s) presented in this entry',
 'No hemolysis information or data found in the reference(s) presented in this entry',
 '[Ref.33285267]5% hemolysis against mouse erythrocytes at 256 µM.',
 'No hemolysis information or data found in the reference(s) presented in this entry',
 'Human erythrocytes: 50% Hemolysis>64 µM',
 'No hemolysis information or data found in the reference(s) presented in this entry',
 'No hemolysis information or data found in the reference(s) presented in this entry',
 '[Ref.22521196] MHC10=33.2 μM against human red blood cells',
 'Not available',
 'No hemolysis information or data found in the reference(s) presented in this entry',
 'Not available',
 'No hemolysis information or data found in the reference(s) presented in this entry',
 'No hemolysis information or data found in the reference(s) presented in this entry',
 '[Ref.10527878] 0% hemolysis at 100 μM against human red blood cells']

In [8]:
import os
clean_df.to_csv(
    "clean_amp_dataset.csv",
    index=False
)

print("Saved:", clean_df.shape)

Saved: (8400, 6)

In [9]:
clean_df["Hemolytic_activity"].value_counts().head(50)

Hemolytic_activity
No hemolysis information or data found in the reference(s) presented in this entry                                                                                                              4898
Not available                                                                                                                                                                                   1432
[Ref.22029824] It shows no hemolytic activity against human red blood cells at the concentration of 50 μg/mL.                                                                                     31
RBC: IC50 ≥ 65 µM                                                                                                                                                                                 28
[Ref.31276398] MHC>128μM. The minimum hemolytic concentration (MHC) is measured as the lowest concentration of the peptides that caused 5% hemolysis of human red blood cells (hRBCs).            20
Human erythrocytes: HC50>200 µM                                                                                                                                                                   18
Rat erythrocytes: IC50>200 μM                                                                                                                                                                     18
[Ref.26998557] LC50>400 μM against human red blood cells                                                                                                                                          14
[Ref.19591185]LC50>200 μM against rat red blood cells                                                                                                                                             13
[Ref.24957834] Some peptides at 50 μM led to about 10% hemolysis against human red blood cells, but in general, negligible hemolytic activity is observed even at 100 μM and 200 μM peptide.      13
[Ref.23894079] MHC10>1280 μM against human red blood cells                                                                                                                                        13
Human erythrocytes: <5% Hemolysis=100 µg/ml                                                                                                                                                       13
Rabbit red blood cells: modest hemolytic activity(as show in Fig.2)                                                                                                                               12
[Ref:22029824] Not found in the literature                                                                                                                                                        12
[Ref.31163671] 10% hemolysis at >100  μg/mL against human blood cells.                                                                                                                            12
[Ref.33285267]0% hemolysis against mouse erythrocytes at 256 µM.                                                                                                                                  11
[Ref.27060618] HC50>500μM against human red blood cells                                                                                                                                           11
Human red blood cells:  no hemolytic activity(as show in Fig.4)                                                                                                                                   10
Human erythrocytes: <10% Hemolysis\t=40 µM                                                                                                                                                         9
Rabbit red blood cells: very low hemolytic activity even at the concentration of 160 μm(as show in fig.3)                                                                                          9
[Ref.23085001] HC50>128 μM against human red blood cells                                                                                                                                           8
Sheep erythrocytes: No hemolysis up tp 500 µg/ml                                                                                                                                                   8
[Ref:11835991]Little hemolytic activity at 50 μg/ml against red blood cells                                                                                                                        7
[Ref.23894079] MHC10=1.25 μM against human red blood cells                                                                                                                                         7
[Ref.31199117] 5% hemolysis at 63μM, 8% hemolysis at 128μM against human red blood cells                                                                                                           7
[Ref:11835991]90–100% hemolytic activity at 50 μg/ml against rabbit red blood cells                                                                                                                7
[Ref.32698035] HC10 > 256 μM. Note: HC10 is the peptide concentration that caused 10% hemolysis of sheep red blood cells (sRBCs).                                                                  7
Human erythrocytes: <5% Hemolysis=64 µM                                                                                                                                                            7
[Ref:17272268]Non-hemolytic activity against rabbit red blood cells                                                                                                                                6
Human erythrocytes: 50% Hemolysis>256 µg/ml                                                                                                                                                        6
Human erythrocytes: 50% Hemolysis>64µM                                                                                                                                                             6
[Ref.8163497]LC50>100 µM against human erythrocytes                                                                                                                                                6
Human erythrocytes: <10% Hemolysis=50 µM                                                                                                                                                           6
[Ref.24105706] HC50>800 μM against human red blood cells                                                                                                                                           6
[Ref.18586467] MHC=128 μM against human red blood cells                                                                                                                                            6
[Ref.20718719]human red cells:HC50>100 µM.                                                                                                                                                         6
Human erythrocytes:0% Hemolysis=25-200 µM                                                                                                                                                          5
Human erythrocytes: Not active up to 500 µg/ml                                                                                                                                                     5
Human RBCs: less than 6% hemolysis at 100 μg/ml                                                                                                                                                    5
[Ref.31194548] 0% hemolysis at 40μM against human blood cells.                                                                                                                                     5
[Ref.30538681] MHC>128μM against human blood cells.The minimum hemolytic concentration (MHC) is defined as the peptide concentration resulting in 5% hemolysis.                                    5
Human erythrocytes: Not active up to 400 µM                                                                                                                                                        5
[Ref:22029824]Not found                                                                                                                                                                            5
[Ref.23894079] MHC10>640 μM against human red blood cells                                                                                                                                          5
[Ref.25494332] HC50>256 μM against human red blood cells                                                                                                                                           5
[Ref.25735802] MHC5>256 μM against human red blood cells                                                                                                                                           5
[Ref.24621994] MHC10>128 μM against human red blood cells                                                                                                                                          5
Human erythrocytes: 50% Hemolysis>36 µM                                                                                                                                                            5
Human red blood cells: MHC>334.4 μmol/L                                                                                                                                                            4
[Ref:22029824]Non-hemolytic activity against human red blood cells                                                                                                                                 4
Name: count, dtype: int64