In [1]:
!pip install biopython peptide -q

In [9]:
#properties extraction for clean_amp dataset

import pandas as pd

amp_df = pd.read_csv(
    "../data/processed_data&code/clean_amp_dataset.csv"
)

print(amp_df.shape)

(8400, 6)

In [10]:
#resuable function for extracting properties

from Bio.SeqUtils.ProtParam import ProteinAnalysis
import pandas as pd
from tqdm import tqdm

def net_charge(seq):

    positive = seq.count("K") + seq.count("R")
    negative = seq.count("D") + seq.count("E")

    return positive - negative


def extract_properties(df, sequence_col="Sequence"):

    properties = []

    for seq in tqdm(df[sequence_col]):

        try:

            analysis = ProteinAnalysis(seq)

            properties.append({

                "Length": len(seq),

                "MolecularWeight":
                    analysis.molecular_weight(),

                "Aromaticity":
                    analysis.aromaticity(),

                "InstabilityIndex":
                    analysis.instability_index(),

                "IsoelectricPoint":
                    analysis.isoelectric_point(),

                "Hydrophobicity":
                    analysis.gravy(),

                "NetCharge":
                    net_charge(seq)

            })

        except:

            properties.append({

                "Length": None,
                "MolecularWeight": None,
                "Aromaticity": None,
                "InstabilityIndex": None,
                "IsoelectricPoint": None,
                "Hydrophobicity": None,
                "NetCharge": None

            })

    return pd.DataFrame(properties)

In [11]:
amp_df = pd.read_csv(
    "../data/processed_data&code/clean_amp_dataset.csv"
)

amp_properties = extract_properties(amp_df)

print(amp_properties.shape)

amp_properties.to_csv(
    "amp_properties.csv",
    index=False
)

print("AMP properties saved")

100%|████████████████████████████████████| 8400/8400 [00:00<00:00, 18786.73it/s]

(8400, 7)
AMP properties saved

In [12]:
#properties extraction for amp_nonamp dataset

amp_nonamp_df = pd.read_csv(
    "../data/processed_data&code/amp_nonamp_dataset.csv"
)

print(amp_nonamp_df.shape)
amp_nonamp_df.head()

(16800, 2)

                          Sequence  label
0  ISGINASVVNIQKEIDRLNEVAKNLNESLIK      1
1                           WAIVLL      1
2                INVLGILGLLGKALSHL      1
3                           FPPWVL      1
4                AVTSSVADTTTVVRDDF      0

In [13]:
amp_nonamp_properties = extract_properties(
    amp_nonamp_df,
    sequence_col="Sequence"
)

print(amp_nonamp_properties.shape)

amp_nonamp_properties.head()

100%|██████████████████████████████████| 16800/16800 [00:00<00:00, 31625.96it/s]

(16800, 7)

,Length,MolecularWeight,Aromaticity,InstabilityIndex,IsoelectricPoint,Hydrophobicity,NetCharge
0,31.0,3422.8823,0.000000,28.367742,6.255324,-0.125806,0.0
1,6.0,713.9069,0.166667,-30.866667,5.525000,2.866667,0.0
2,17.0,1731.1304,0.000000,10.752941,8.757208,1.482353,1.0
3,6.0,757.9180,0.333333,53.583333,5.525000,1.116667,0.0
4,17.0,1783.8870,0.058824,-2.523529,4.050028,0.223529,-2.0

In [14]:
amp_nonamp_properties.to_csv(
    "amp_nonamp_properties.csv",
    index=False
)

print("Saved")

Saved

In [15]:
#properties for hemolysis metadata
hemo_df = pd.read_csv(
    "../embeddings/hemo_metadata.csv"
)

print(hemo_df.shape)

(1509, 8)

In [16]:
hemo_properties = extract_properties(
    hemo_df,
    sequence_col="Sequence"
)

print(hemo_properties.shape)

100%|████████████████████████████████████| 1509/1509 [00:00<00:00, 17548.22it/s]

(1509, 7)

In [17]:
hemo_properties.to_csv(
    "hemo_properties.csv",
    index=False
)